### ISSUE TITLE
What the fuck is a closure

### ISSUE THREAD

**Issue by juanpablomarin** [gaearon/whatthefuck.is#1]

**Comment by gaearon** [comment]
Good choice.

**Comment by yashguptaz** [comment]
I wrote a blog post about closures :)
https://dev.to/yashguptaz/disclosure-of-javascript-closures-1ac8

**Comment by gaearon** [comment]
https://whatthefuck.is/closure

**Comment by juanpablomarin** [comment]
Wicked explanation 👍🏼

**Comment by ogrotten** [comment]
Excellent explanation, excellent format.

- Terse introduction.
- Terse explanation.
- "You can stop reading here".
- In-depth continuation.

Not a lot of that going on these days. This format would make it infinitely useful.
