### ISSUE TITLE
Branch for mirror site

### ISSUE THREAD

**Issue by daydream05** [gaearon/whatthefuck.is#115]
Hi Dan,

So I saw there's a request for non-cuss version of the site on Twitter.

I forked the site and bought [whatthefork.is ](https://whatthefork.is) -- a nod to The Good Place.

I think it would be easier if there's a branch for this mirror(and other mirrors), so everything is in one place.

**Comment by gaearon** [comment]
Can we set it up in an automated way with text replacement, like this? 

https://twitter.com/wesbos/status/1283043262790602753

**Comment by gaearon** [comment]
And I'll need to fix JS to not hardcode the name.

**Comment by vebradev** [comment]
@daydream05 👋  I've noticed that title still has a curse word in it.

**Comment by MillyCodes** [comment]
I like this ...I can access it at work, the vpn blocks the original site. 😅

**Comment by victorias** [comment]
This is great :) it will also make it easier for kids to access the site.

**Comment by daydream05** [comment]
Woops will fix it. Just rushed it. 

@gaearon i’ll look into that! I just forked for now as it seems the easiest way to go about it. And i’ll just manually update from the original repo.

**Comment by gaearon** [comment]
Great. I'd be happy to link in the footer.

**Comment by FezVrasta** [comment]
The RSS feed links still point to the original domain

**Comment by daydream05** [comment]
@FezVrasta just fixed! Everything should be forks now.

**Comment by daydream05** [comment]
Hey all, here's the repo for the mirror:

https://github.com/daydream05/whatthefuck.is

What I'm doing:
- Manually merging the Dan's branch to my repo everytime he makes an update.
- I plan to do this at the end of the day every day or whenever I have time during the day.

If you'd like to help me figure out how to do this automatically or would like to help me do it manually. That would be great! 

There's also another way which is using Cloudflare as Dan mentioned:
https://twitter.com/wesbos/status/1283043262790602753

If you figure that out feel free to DM me! I'd be happy to transfer you the domain name.

**Comment by daydream05** [comment]
I should probably add a `rel=canonical` tag on my mirror so we don't get penalized by Google and all that SEO juice goes back to you.

**Comment by gaearon** [comment]
I trust you to figure out how that should work! I added a link in the footer.
https://github.com/gaearon/whatthefuck.is/commit/24c5119b46c0368923ef440195902f0477edd251

Would be nice to integrate it more "natively" somehow but not sure where it could fit in the design.

**Comment by daydream05** [comment]
Sweet! I modified it on my end to link back to the original site.

**Comment by gaearon** [comment]
Seems like this is solved. Thanks so much @daydream05 for taking this on. Truly appreciated.

**Comment by dimaip** [comment]
Thank you so much @daydream05!
