### ISSUE TITLE
Code snippets are on one line

### ISSUE THREAD

**Issue by mitchellsimoens** [gaearon/whatthefuck.is#69]
The code snippets in the closure markdown is multi lines. Example: https://github.com/gaearon/whatthefuck.is/blob/main/posts/closure.md However, when rendered out the snippets are on one line. Here is a screenshot with left is the markdown as rendered by GitHub, right is from https://whatthefuck.is/closure

![Screen Shot 2020-07-14 at 8 55 35 AM](https://user-images.githubusercontent.com/325473/87428121-dca57100-c5af-11ea-9469-5548baf5719b.png)

**Comment by gaearon** [comment]
We'd need to know more — what browser, OS?

**Comment by mitchellsimoens** [comment]
macOS 10.15.5
Firefox 78.0.2 (latest stable)

Looks fine on Chrome 83 and Safari 13.1.1

**Comment by gaearon** [comment]
Curious.

**Comment by mitchellsimoens** [comment]
Looks like the HTML is different in Firefox:

<img width="426" alt="firefox" src="https://user-images.githubusercontent.com/325473/87428737-cfd54d00-c5b0-11ea-9aff-e24e67ce761d.png">

Than in Chrome (notice the `div`s):

<img width="369" alt="Screen Shot 2020-07-14 at 9 02 46 AM" src="https://user-images.githubusercontent.com/325473/87428775-d95eb500-c5b0-11ea-8c8e-3c403b0ab4ad.png">

**Comment by deflock** [comment]
It's okay in Firefox 78.0.2 and 79.0b7 on Windows 10.
Try in clean profile with no addons if any

**Comment by fnky** [comment]
Works fine in Firefox 74.0 and 78.0.2 on macOS Mojave (10.14.5). Must be an addon that trims your divs 👀

**Comment by mitchellsimoens** [comment]
Huh, that'd be odd but yea, testing in a private window it renders fine. Will disable addons one by one to see if I can find a culprit...

**Comment by mitchellsimoens** [comment]
Ok, looks like it's the [axe addon](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/). Wonder what/why it's doing.
