### ISSUE TITLE
Page size + Consider using a different site generator

### ISSUE THREAD

**Issue by dmitriid** [gaearon/whatthefuck.is#91]
As of July 14, 2020:

https://whatthefuck.is/closure

If we remove React Devtools (injected by the extension), it's still a dozen of .js includes with over 100 KB of JS to display a single static page that is nothing but text:

<img width="1239" alt="Screenshot 2020-07-14 at 16 01 31" src="https://user-images.githubusercontent.com/32768/87435117-97069980-c5eb-11ea-8ada-248506ddb554.png">
<img width="800" alt="Screenshot 2020-07-14 at 16 03 18" src="https://user-images.githubusercontent.com/32768/87435130-9b32b700-c5eb-11ea-93cd-999ccdb86e81.png">

**Comment by gaearon** [comment]
I believe I've covered this sufficiently here.
https://twitter.com/dan_abramov/status/1283043711866339330
